[project]
name = "homework-1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cvxpy>=1.7.3",
    "ecos>=2.0.14",
    "matplotlib>=3.10.6",
    "numpy>=2.3.3",
    "typing>=3.10.0.0",
]
